// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // Add default cases for unsupported platforms
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoPGXNLntlnc0RYUvRTyEuyJZVuUM5F98',
    appId: '1:28697088278:web:545952a8bfd55dffe4c037',
    messagingSenderId: '28697088278',
    projectId: 'flutter-project-tek5',
    authDomain: 'flutter-project-tek5.firebaseapp.com',
    storageBucket: 'flutter-project-tek5.appspot.com',
    measurementId: 'G-ED82C0Y8LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdiq_8oerxmshCrQSJ-QYuIAGdbo2BPKI',
    appId: '1:28697088278:android:9115228a39201f85e4c037',
    messagingSenderId: '28697088278',
    projectId: 'flutter-project-tek5',
    storageBucket: 'flutter-project-tek5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNT1rLrRNlHq96JJSkCiFDZLFedoe7Xk8',
    appId: '1:28697088278:ios:e439fa9c741c5a61e4c037',
    messagingSenderId: '28697088278',
    projectId: 'flutter-project-tek5',
    storageBucket: 'flutter-project-tek5.appspot.com',
    iosClientId:
        '28697088278-nmm8ps1uq9t0m97ejrf49u042fa82l1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNT1rLrRNlHq96JJSkCiFDZLFedoe7Xk8',
    appId: '1:28697088278:ios:e439fa9c741c5a61e4c037',
    messagingSenderId: '28697088278',
    projectId: 'flutter-project-tek5',
    storageBucket: 'flutter-project-tek5.appspot.com',
    iosClientId:
        '28697088278-nmm8ps1uq9t0m97ejrf49u042fa82l1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramFlutter',
  );
}
